from enum import Enum
class RemoteTypes(Enum):
	"""These are all the cloud systems support by rclone (generated with v1.63.1).
	A more detailed overview can be found here: https://rclone.org/overview/
	"""
	amazon_cloud_drive="amazon cloud drive"
	azureblob="azureblob"
	b2="b2"
	box="box"
	crypt="crypt"
	cache="cache"
	chunker="chunker"
	combine="combine"
	compress="compress"
	drive="drive"
	dropbox="dropbox"
	fichier="fichier"
	filefabric="filefabric"
	ftp="ftp"
	google_cloud_storage="google cloud storage"
	google_photos="google photos"
	hasher="hasher"
	hdfs="hdfs"
	hidrive="hidrive"
	http="http"
	internetarchive="internetarchive"
	jottacloud="jottacloud"
	koofr="koofr"
	local="local"
	mailru="mailru"
	mega="mega"
	memory="memory"
	netstorage="netstorage"
	onedrive="onedrive"
	opendrive="opendrive"
	oracleobjectstorage="oracleobjectstorage"
	pcloud="pcloud"
	pikpak="pikpak"
	premiumizeme="premiumizeme"
	putio="putio"
	qingstor="qingstor"
	s3="s3"
	seafile="seafile"
	sftp="sftp"
	sharefile="sharefile"
	sia="sia"
	smb="smb"
	storj="storj"
	tardigrade="tardigrade"
	sugarsync="sugarsync"
	swift="swift"
	union="union"
	uptobox="uptobox"
	webdav="webdav"
	yandex="yandex"
	zoho="zoho"