from enum import Enum


class RemoteTypes(Enum):
    """These are all the cloud systems support by rclone (generated with v1.64.0).
    A more detailed overview can be found here: https://rclone.org/overview/
    """

    memory = "memory"
    crypt = "crypt"
    hdfs = "hdfs"
    local = "local"
    protondrive = "protondrive"
    storj = "storj"
    tardigrade = "tardigrade"
    fichier = "fichier"
    ftp = "ftp"
    http = "http"
    internetarchive = "internetarchive"
    koofr = "koofr"
    mega = "mega"
    netstorage = "netstorage"
    opendrive = "opendrive"
    qingstor = "qingstor"
    seafile = "seafile"
    sftp = "sftp"
    sia = "sia"
    smb = "smb"
    sugarsync = "sugarsync"
    uptobox = "uptobox"
    webdav = "webdav"
    filefabric = "filefabric"
    azureblob = "azureblob"
    b2 = "b2"
    quatrix = "quatrix"
    cache = "cache"
    chunker = "chunker"
    combine = "combine"
    compress = "compress"
    hasher = "hasher"
    oracleobjectstorage = "oracleobjectstorage"
    s3 = "s3"
    swift = "swift"
    union = "union"
    amazon_cloud_drive = "amazon cloud drive"
    dropbox = "dropbox"
    google_photos = "google photos"
    hidrive = "hidrive"
    jottacloud = "jottacloud"
    mailru = "mailru"
    onedrive = "onedrive"
    pcloud = "pcloud"
    pikpak = "pikpak"
    premiumizeme = "premiumizeme"
    putio = "putio"
    sharefile = "sharefile"
    yandex = "yandex"
    zoho = "zoho"
    box = "box"
    drive = "drive"
    google_cloud_storage = "google cloud storage"
