name: Run Unit Test via Pytest  
  
on: [push]
env:
  rclone_config: ${{ secrets.RCLONE_CONFIG }}
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: install the rclone software
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
      - name: Setup rclone config file
        run: |
            mkdir -p ~/.config/rclone
            rclone config file
            echo $rclone_config | base64 -d > ~/.config/rclone/rclone.conf
            rclone listremotes
            rclone config file
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest
      - name: Run test suite  
        run: |  
          pytest -v
      - name: Update GH rclone file
        run:  cat ~/.config/rclone/rclone.conf | gh secret set RCLONE_CONFIG
        env:
            rclone_config_secret_name: RCLONE_CONFIG
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}
            GH_REPO: ${{ github.repository }}
            
