name: Run Unit Test via Pytest  
  
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:  
  build:  
    runs-on: ubuntu-latest
    env:
      python_version: "3.10"
      timezone: "Europe/Berlin"
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ env.python_version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ env.python_version }}    
      - name: Install the rclone software
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
      - name: Setup s3 test-server and rclone
        run: |
            ./launch_test_server.sh
      - name: Set timezone
        run: |
            sudo timedatectl set-timezone ${{ env.timezone }}
            timedatectl
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
          pip install pytest
      - name: Run test suite  
        run: |  
          pytest -v